version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password
      MYSQL_DATABASE: userschema        # Database to create (optional)
    ports:
      - "3308:3306"  # Exposes MySQL on port 3308 of the host
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - patient

  # Redis Cache
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - patient

  # HashiCorp Consul
  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - '8500:8500'
    networks:
      - patient

  # Kafka and Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - patient

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "29092:29092"
    networks:
      - patient

  # Spring Cloud Config Server
  config-server:
    image: mathanparamasivan/config-server:latest
    container_name: config-server
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/mathanparamasivan/central-config-repo # Replace with actual Git repo URL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_SERVER_PORT: 8888
      LATEST_PROP: latest
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    restart: always
    networks:
      - patient

volumes:
  mysql-data:

networks:
  patient:
    driver: bridge
