spring:
  application:
    name: userrole  # Name of the application
  cloud:
    config:
      uri: http://localhost:8888  # URI of the Spring Cloud Config Server
  config:
    import: configserver:http://localhost:8888  # Explicitly import the configuration from Config Server
  profiles:
    active: dev  # Active profile (this fetches the dev-specific configuration)

management:
  endpoints:
    web:
      exposure:
        include: refresh  # Exposes the /actuator/refresh endpoint to trigger configuration refresh
logging:
  level:
    org.springframework.cache: DEBUG