spring:
  application:
    name: userrole
  cloud:
    vault:
      uri: http://127.0.0.1:8200  # Vault server URI
      token: #hvs.CAESILvggMjVuvex2YLif7VJABwQftpaKTw_8MOpY0GgzUOsGh4KHGh2cy5PYnExWHVmNkRHeE1obHJpalBWdUxCUjA  # Vault token you generated
      authentication: token
      kv:
        enabled: true
        backend: secret
        default-context: mysql  # This should be the correct path
  datasource:
    url: jdbc:mysql://localhost:3306/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root #${vault.secret.data.data.mysql.username}  # Corrected path
    password: Verithanam@123 #${vault.secret.data.data.mysql.password}  # Corrected path
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update  # Options: none, validate, update, create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8084
