spring:
  application:
    name: userrole  # Name of the application
  cloud:
    config:
      uri: http://172.26.192.1:8888  # URI of the Spring Cloud Config Server
  config:
    import: configserver:http://172.26.192.1:8888  # Explicitly import the configuration from Config Server

management:
  endpoints:
    web:
      exposure:
        include: refresh  # Exposes the /actuator/refresh endpoint to trigger configuration refresh
